### ISSUE TITLE
Installation instructions bring some other library

### ISSUE THREAD

**Issue by scoricov** [MarioVilas/googlesearch#114] opened 2023-02-05 17:11 UTC
When using command from the README to install this module 'pip install google', a module will be installed, but its code will be of some other repository. Likely this is `https://github.com/anthonyhseb/googlesearch`

As a result, other instructions in the docs won't work as well.

Alternatively, this worked for me:
```
pip3 install -e git+https://github.com/MarioVilas/googlesearch#egg=google
```

**Comment by MarioVilas** [comment] 2023-02-06 12:21
That is very odd, because the package in PyPi is definitely mine: https://pypi.org/project/google/

**Comment by MarioVilas** [comment] 2024-03-16 10:11
Issue is very old and could not reproduce, closing now.

**Closed by MarioVilas** 2024-03-16 10:11 UTC
