### ISSUE TITLE
No such file or directory: '/home/wsgi/.google-cookie'

### ISSUE THREAD

**Issue by dsc03** [MarioVilas/googlesearch#53] opened 2018-09-12 20:47 UTC
Hi Mario,

Thanks for putting time into building this. It's been incredibly useful for me to use. I'm trying to run your package from a remote AWS EC2 instance and I've actually been unable to because I get the following error:

```
<type 'exceptions.IOError'>
[Errno 2] No such file or directory: '/home/wsgi/.google-cookie'
```

I looked through your source code and saw that you actually do reference .google-cookie here:

```
cookie_jar = LWPCookieJar(os.path.join(home_folder, '.google-cookie'))
try:
      cookie_jar.load()
except Exception:
```

I haven't been able to figure out how to get this working on my EC2 instance. Do you have any suggestions for what the issue is? Is there a specific cookie I need to add to my environment? Any help you can provide would be greatly appreciated. 

Thanks.

-Daniel

**Comment by MarioVilas** [comment] 2018-09-13 09:54
Hi! Thanks for your kind words :)

I'm afraid I don't know much about EC2 instances, but it looks like for some reason the home directory cannot be accessed. As a quick and dirty patch I'd suggest replacing the home_folder variable with "/tmp" and try it out...

**Comment by dsc03** [comment] 2018-09-13 16:52
I'll definitely give that a shot! So I was looking through the source code and saw that variable. Additionally, I saw the LWPCookieJar. What's strange is that when I search for the folder 'users/myname/.google-cookie' on my own computer, although the code works correctly, I can't find that '.google-cookie' file anywhere. 

Does this file get created and then deleted once it is done being used? I was looking through some of the Cookie Jar documentation, but I couldn't get a clear answer on how this was working.

**Comment by MarioVilas** [comment] 2018-09-14 08:45
It should not be deleted, but then again it should also fail silently, since the LWPCookieJar class is not supposed to access the file until you call load(). I can only guess you're getting the exception because it does access the file before that for some reason. :(

**Comment by Zhipeng-Chang** [comment] 2018-10-28 20:02
This issue should be fixed by my last pull request!

**Comment by MarioVilas** [comment] 2018-11-06 09:59
I do not use AWS so I've no way to reproduce this :(

**Comment by MarioVilas** [comment] 2019-02-03 13:54
Stack trace, reported privately via email:
```
[Thu Jan 31 14:15:28.008076 2019] [:error] [pid 3359] [remote 151.230.55.234:56]   File "/opt/python/current/app/application.py", line 86, in generate_URL_list
[Thu Jan 31 14:15:28.008078 2019] [:error] [pid 3359] [remote 151.230.55.234:56]     for url in search(query, tld = "co.uk", lang='en', pause = 2, stop=n): #can also add tld to limit to country e.g. tld='uk
[Thu Jan 31 14:15:28.008081 2019] [:error] [pid 3359] [remote 151.230.55.234:56]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/googlesearch/__init__.py", line 330, in search
[Thu Jan 31 14:15:28.008083 2019] [:error] [pid 3359] [remote 151.230.55.234:56]     get_page(url_home % vars())
[Thu Jan 31 14:15:28.008085 2019] [:error] [pid 3359] [remote 151.230.55.234:56]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/googlesearch/__init__.py", line 151, in get_page
[Thu Jan 31 14:15:28.008088 2019] [:error] [pid 3359] [remote 151.230.55.234:56]     cookie_jar.save()
[Thu Jan 31 14:15:28.008090 2019] [:error] [pid 3359] [remote 151.230.55.234:56]   File "/usr/lib64/python3.6/http/cookiejar.py", line 1875, in save
[Thu Jan 31 14:15:28.008092 2019] [:error] [pid 3359] [remote 151.230.55.234:56]     with open(filename, "w") as f:
[Thu Jan 31 14:15:28.008096 2019] [:error] [pid 3359] [remote 151.230.55.234:56] FileNotFoundError: [Errno 2] No such file or directory: '/home/wsgi/.google-cookie'
```

**Comment by MarioVilas** [comment] 2019-12-05 15:07
Fixed in master.

**Closed by MarioVilas** 2019-12-05 15:07 UTC
Labels: bug
